### PR TITLE
Improve pagination handling

### PR DESCRIPTION
**Pull request by tesence**
* **Please check if the PR fulfills these requirements**
- [x] Tests have been conducted on the PR
- [ ] Docs have been added / updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix the pagination not working and make it generic.

* **What is the current behavior?** (You can also link to an open issue here)
The pagination is only supported for the endpoint "/streams", in the method get_streams.

* **What is the new behavior (if this is a feature change)?**
The pagination is now indenpendent of the rest and can be used for any endpoint. We now use a recursive behaviour instead of a while loop.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
N/A

* **Other information**:
N/A

### CODE REVIEW

**Comment by tesence** [comment]
Note: It could be nice to have a @pagination decorator instead of a format method, but I don't know how to build a decorator for instance methods

**Comment by tesence** [comment]
Fair enough, I'll switch back to a while loop. 
Also about the error handling I feel like a custom request method would be required. A method that just calls `_session.get` and handles the different status codes: 200 to 299, 400 to 499 and 500 to 599, everything inside a `try/except` block

**Comment by EvieePy** [comment]
If you would like to easily discuss things you can join our [Discord Server](http://discord.gg/JhW28zp)

**Comment by tesence** [comment]
- Back to a while loop
- Every request is now made using a custom `get` method that handles HTTP/aiohttp exceptions (and pagination still)

**Comment by EvieePy** [comment]
Thanks :+1:

**Pull request merged**
